const form=document.querySelector('#unlock-form');const input=document.querySelector('#password');const statusEl=document.querySelector('#status');const lock=document.querySelector('#lock');const gift=document.querySelector('#gift');const frame=document.querySelector('#gift-frame');const musicButton=document.querySelector('#music-button');let audio=null;let frameUrl=null;let musicReady=false;const mediaUrls=[];
const bytes=(buffer,start,length)=>new Uint8Array(buffer,start,length);
async function derive(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt'])}
async function download(name,onProgress){const response=await fetch(name,{cache:'force-cache'});if(!response.ok)throw new Error('network');if(!response.body||!onProgress)return response.arrayBuffer();const total=Number(response.headers.get('content-length'))||0;const reader=response.body.getReader();const chunks=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;if(total)onProgress(Math.round(received/total*100))}const packed=new Uint8Array(received);let offset=0;for(const chunk of chunks){packed.set(chunk,offset);offset+=chunk.length}return packed.buffer}
async function decompress(compressed){if('DecompressionStream'in window){const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).text()}if(window.fflate){const data=await new Promise((resolve,reject)=>fflate.gunzip(new Uint8Array(compressed),(error,value)=>error?reject(error):resolve(value)));return new TextDecoder().decode(data)}throw new Error('browser')}
async function unpack(name,password,onProgress){const packed=await download(name,onProgress);const magic=new TextDecoder().decode(bytes(packed,0,5));if(magic!=='GIFT1')throw new Error('format');const salt=bytes(packed,5,16);const iv=bytes(packed,21,12);const tag=bytes(packed,33,16);const encrypted=bytes(packed,49);const combined=new Uint8Array(encrypted.length+tag.length);combined.set(encrypted);combined.set(tag,encrypted.length);const key=await derive(password,salt);const compressed=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,combined);return JSON.parse(await decompress(compressed))}
function toBlobUrl(dataUrl){const comma=dataUrl.indexOf(',');const mime=(dataUrl.slice(0,comma).match(/^data:([^;]+)/)||[])[1]||'application/octet-stream';const raw=atob(dataUrl.slice(comma+1));const data=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)data[i]=raw.charCodeAt(i);const url=URL.createObjectURL(new Blob([data],{type:mime}));mediaUrls.push(url);return url}
function unlockAudio(){const data=new Uint8Array(8044);const view=new DataView(data.buffer);const text=(at,value)=>{for(let i=0;i<value.length;i++)data[at+i]=value.charCodeAt(i)};text(0,'RIFF');view.setUint32(4,8036,true);text(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,8000,true);view.setUint16(32,1,true);view.setUint16(34,8,true);text(36,'data');view.setUint32(40,8000,true);data.fill(128,44);const url=URL.createObjectURL(new Blob([data],{type:'audio/wav'}));mediaUrls.push(url);audio=new Audio(url);audio.loop=true;audio.volume=0;audio.play().catch(()=>{})}
function deliverVideo(src){const send=()=>frame.contentWindow&&frame.contentWindow.postMessage({type:'gift-video',src},'*');if(frame.contentDocument&&frame.contentDocument.readyState==='complete')send();else frame.addEventListener('load',send,{once:true})}
async function loadVideo(password){try{const payload=await unpack('payload-video.bin',password);deliverVideo(toBlobUrl(payload.video))}catch(error){}}
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');const password=input.value;button.disabled=true;input.disabled=true;unlockAudio();statusEl.textContent='正在打开回忆…';const musicTask=unpack('payload-music.bin',password).then(async music=>{audio.pause();audio.src=toBlobUrl(music.music);audio.loop=true;audio.volume=1;audio.load();musicReady=true;try{await audio.play();return true}catch(error){return false}}).catch(()=>null);try{const payload=await unpack('payload-core.bin',password,percent=>{statusEl.textContent=`正在打开回忆… ${percent}%`});frameUrl=URL.createObjectURL(new Blob([payload.html],{type:'text/html;charset=utf-8'}));frame.src=frameUrl;musicButton.textContent='♫ 音乐加载中…';lock.hidden=true;gift.hidden=false;document.title='回忆之旅';musicTask.then(playing=>{musicButton.textContent=playing===null?'♫ 音乐加载失败':playing?'♫ 音乐播放中':'♫ 点击播放音乐'});loadVideo(password)}catch(error){if(audio)audio.pause();statusEl.textContent=error.message==='network'?'暂时没有连接上，请稍后再试。':error.message==='browser'?'请换用系统浏览器或升级后再试。':'车票好像不对，再想一想吧。';button.disabled=false;input.disabled=false;input.focus();input.select()}});
musicButton.addEventListener('click',async()=>{if(!audio||!musicReady)return;if(audio.paused)await audio.play().catch(()=>{});else audio.pause();musicButton.textContent=audio.paused?'♫ 播放音乐':'♫ 音乐播放中'});
addEventListener('beforeunload',()=>{if(frameUrl)URL.revokeObjectURL(frameUrl);for(const url of mediaUrls)URL.revokeObjectURL(url)});
