const form=document.querySelector('#unlock-form');const input=document.querySelector('#password');const statusEl=document.querySelector('#status');const lock=document.querySelector('#lock');const gift=document.querySelector('#gift');const frame=document.querySelector('#gift-frame');const musicButton=document.querySelector('#music-button');let audio=null;let frameUrl=null;
const bytes=(buffer,start,length)=>new Uint8Array(buffer,start,length);
async function derive(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt'])}
async function download(name,onProgress){const response=await fetch(name,{cache:'force-cache'});if(!response.ok)throw new Error('network');if(!response.body||!onProgress)return response.arrayBuffer();const total=Number(response.headers.get('content-length'))||0;const reader=response.body.getReader();const chunks=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;if(total)onProgress(Math.round(received/total*100))}const packed=new Uint8Array(received);let offset=0;for(const chunk of chunks){packed.set(chunk,offset);offset+=chunk.length}return packed.buffer}
async function unpack(name,password,onProgress){const packed=await download(name,onProgress);const magic=new TextDecoder().decode(bytes(packed,0,5));if(magic!=='GIFT1')throw new Error('format');const salt=bytes(packed,5,16);const iv=bytes(packed,21,12);const tag=bytes(packed,33,16);const encrypted=bytes(packed,49);const combined=new Uint8Array(encrypted.length+tag.length);combined.set(encrypted);combined.set(tag,encrypted.length);const key=await derive(password,salt);const compressed=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,combined);if(!('DecompressionStream'in window))throw new Error('browser');const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'));const text=await new Response(stream).text();return JSON.parse(text)}
function deliverVideo(src){const send=()=>frame.contentWindow&&frame.contentWindow.postMessage({type:'gift-video',src},'*');if(frame.contentDocument&&frame.contentDocument.readyState==='complete')send();else frame.addEventListener('load',send,{once:true})}
async function loadVideo(password){try{const payload=await unpack('payload-video.bin',password);deliverVideo(payload.video)}catch{}}
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');const password=input.value;button.disabled=true;input.disabled=true;statusEl.textContent='正在加载背景音乐…';try{const music=await unpack('payload-music.bin',password,percent=>{statusEl.textContent=`正在加载背景音乐… ${percent}%`});audio=new Audio(music.music);audio.loop=true;await audio.play().catch(()=>{});statusEl.textContent='音乐已就绪，正在打开回忆…';const payload=await unpack('payload-core.bin',password,percent=>{statusEl.textContent=`音乐已就绪，正在打开回忆… ${percent}%`});frameUrl=URL.createObjectURL(new Blob([payload.html],{type:'text/html;charset=utf-8'}));frame.src=frameUrl;musicButton.textContent=audio.paused?'♫ 点击播放音乐':'♫ 音乐播放中';lock.hidden=true;gift.hidden=false;document.title='基友限定 · 回忆放映厅';loadVideo(password)}catch(error){statusEl.textContent=error.message==='network'?'暂时没有连接上，请稍后再试。':error.message==='browser'?'请使用最新版 Chrome、Edge 或 Safari 打开。':'口令好像不对，再想一想吧。';button.disabled=false;input.disabled=false;input.focus();input.select()}});
musicButton.addEventListener('click',async()=>{if(!audio)return;if(audio.paused)await audio.play().catch(()=>{});else audio.pause();musicButton.textContent=audio.paused?'♫ 播放音乐':'♫ 音乐播放中'});
addEventListener('beforeunload',()=>{if(frameUrl)URL.revokeObjectURL(frameUrl)});
